### ISSUE TITLE
maven package 提示：common library is missing

### ISSUE THREAD

**Issue by mealayaria** [gavin-guo/spring-cloud-demo#1]
你好，我下载了Demo，在本地运行时出现了一点问题，我使用的是idea 2017.1.5，在用maven package  oauth2-server子模块的时候提示了如下报错：

> /usr/lib/jvm/java-8-openjdk/bin/java -Dmaven.multiModuleProjectDirectory=/home/weiss/java/spring-cloud-demo/oauth2-server -Xmx512m -Dmaven.home=/usr/share/intellij-idea-ultimate-edition/plugins/maven/lib/maven3 -Dclassworlds.conf=/usr/share/intellij-idea-ultimate-edition/plugins/maven/lib/maven3/bin/m2.conf -javaagent:/usr/share/intellij-idea-ultimate-edition/lib/idea_rt.jar=40949:/usr/share/intellij-idea-ultimate-edition/bin -Dfile.encoding=UTF-8 -classpath /usr/share/intellij-idea-ultimate-edition/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version=2017.1.5 package

> [INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building oauth2-server 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.gavin:common-library:jar:0.0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.476 s
[INFO] Finished at: 2017-07-17T11:15:53+08:00
[INFO] Final Memory: 22M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project oauth2-server: Could not resolve dependencies for project com.gavin:oauth2-server:jar:0.0.1-SNAPSHOT: Could not find artifact com.gavin:common-library:jar:0.0.1-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

但是在debug模式下却是正常的，现在我不太确定是哪里出了问题，希望能得到你的帮助，谢谢！

update:
        我又尝试使用lifecycle中的package单独打包common library，提示如下（只截取了主要错误行）：

> java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test

然后我又使用maven-jar-plugin中的jar:jar，可以打包成功，然后使用maven-install-plugin中
install：install，提示报错如下：

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-cli) on project common-library: The packaging for this project did not assign a file to the build artifact -> [Help 1]

我现在的问题是，没有main class的公共库该如何打包并安装到local maven repository，尝试了以上方法都不可行，不知道是自己的环境问题，还是操作方式有问题。

**Comment by gavin-guo** [comment]
你好，你需要先在common library的根目录下用mvn clean compile package -DskipTests 命令编译common library的jar文件。

**Comment by mealayaria** [comment]
测试可行，感谢解答！

然后还有一个新的问题，在配置文件中有类似${OAUTH_HOST}、${EUREKA_HOST}的引用，但是我没有找到这些变量的初始配置在哪里，是和docker有关系吗？（个人还没有接触docker，项目中有关docker的部分暂时略过了）

受到项目启发我想在config server中集中管理所有公共的HOST配置，由此产生了一个矛盾：如果我想在config server中获取eureka host，必须先注册到eureka server才能发现config server，但是想要注册到eureka server 必须要到config server中获取配置，关于这一点很是头疼，不知道您有没有什么好的办法呢？

**Comment by gavin-guo** [comment]
${OAUTH_HOST}、${EUREKA_HOST}是读取环境变量。环境变量可以通过Dockerfile、K8s、命令行、系统全局变量中设置。比如linux下export OAUTH_HOST = xxxx
eureka server 的地址必须是实际地址，其他所有服务就在注册到eureka后通过虚拟地址访问。
设置OAUTH_HOST是因为oauth2的标准配置中还不支持虚拟地址访问，可以通过自己在之间再架设一个haproxy之类做路由。

**Comment by mealayaria** [comment]
我从你的Demo中学到了很多新的思路，再次感谢回复！
